using Content.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.Anomalies;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Anomaly.Ui;

/*
 * THIS FILE HAS BEEN BASICALLY ENTIRELY REWRITTEN FOR PERSISTENCE 14
 */

[GenerateTypedNameReferences]
public sealed partial class AnomalyGeneratorWindow : FancyWindow
{
    [Dependency] private IGameTiming _time = default!;
    [Dependency] private IEntityManager _entMan = default!;

    private AnomalyGeneratorBUIState? _state;
    private GeneratorDisplayState _currentDisplayState = GeneratorDisplayState.Unavailable;

    public Action? GenerateAction;

    public AnomalyGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GenerateButton.OnPressed += _ => GenerateAction?.Invoke();
    }

    private enum GeneratorDisplayState
    {
        Ready,
        Generating,
        Cooldown,
        Unavailable
    }

    private void SetDisplayState(GeneratorDisplayState state)
    {
        _currentDisplayState = state;
        GenerateButton.Visible = state is GeneratorDisplayState.Ready or GeneratorDisplayState.Unavailable;

        GenerationBar.Visible = state == GeneratorDisplayState.Generating;
        CooldownBar.Visible = state == GeneratorDisplayState.Cooldown;

        GenerateButton.Disabled = state != GeneratorDisplayState.Ready;
    }

    public void UpdateState(AnomalyGeneratorBUIState state)
    {
        _state = state;

        UpdateFuelPanelState();
        UpdateAnomalyInfoState();
        UpdateStatusBarState();
    }

    private void UpdateFuelPanelState()
    {
        if (_state is not { } state) return;

        if (state.Capsule is { } netCapsule)
        {
            var capsuleUid = _entMan.GetEntity(netCapsule);

            CapsuleView.SetEntity(capsuleUid);
            EjectCapsuleButton.Disabled = false;
        }
        else
        {
            CapsuleView.SetEntity(null);
            EjectCapsuleButton.Disabled = true;
        }

        var completion = Math.Clamp((float)(state.MaterialAmount / state.MaterialRequired), 0f, 1f);

        FuelBar.Value = completion;
        FuelText.Text = $"{state.MaterialAmount} / {state.MaterialRequired}";
    }

    private void UpdateAnomalyInfoState()
    {
        if (_state is not { } state) return;
    }

    private void UpdateStatusBarState()
    {
        if (_state is not { } state) return;
        var displayState = GetDisplayState(state);
        SetDisplayState(displayState);

        if (_currentDisplayState == GeneratorDisplayState.Generating)
            UpdateProgressBar();
        if (_currentDisplayState == GeneratorDisplayState.Cooldown)
            UpdateCooldownBar();
    }

    private void UpdateProgressBar()
    {
        if (_state is not { } state) return;
        if (!state.IsGenerating || state.GenerateEndTime is not { } end) return;

        var remaining = end - _time.CurTime;
        var elapsed = state.GenerateDuration - remaining;

        GenerationBar.Value = Math.Clamp((float)(elapsed / state.GenerateDuration), 0f, 1f);
        GenerationText.Text = $"{Math.Max(remaining.TotalSeconds, 0):0.0}s";
    }

    private void UpdateCooldownBar()
    {
        if (_state is not { } state) return;
        if (!state.IsOnCooldown || state.CooldownEndTime is not { } end) return;
        var remaining = end - _time.CurTime;
        var elapsed = state.CooldownDuration - remaining;

        CooldownBar.Value = Math.Clamp((float)(elapsed / state.CooldownDuration), 0f, 1f);
        CooldownText.Text = $"{remaining.Minutes:0}:{remaining.Seconds:00}";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_currentDisplayState == GeneratorDisplayState.Generating) UpdateProgressBar();
        if (_currentDisplayState == GeneratorDisplayState.Cooldown) UpdateCooldownBar();
    }

    private GeneratorDisplayState GetDisplayState(AnomalyGeneratorBUIState state)
    {
        if (state.IsGenerating) return GeneratorDisplayState.Generating;
        if (state.IsOnCooldown) return GeneratorDisplayState.Cooldown;

        return state.CanGenerateAnomaly ? GeneratorDisplayState.Ready : GeneratorDisplayState.Unavailable;
    }
}