using System.Numerics;
using Content.Shared._Persistence14.Research.ResearchTree;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence14.Research.ResearchTree;

[GenerateTypedNameReferences]
public sealed partial class ResearchTree : PanelContainer
{
    private const float NodeWidth = 100f;
    private const float NodeHeight = 100f;

    private const float HorizontalSpacing = 40f;
    private const float VerticalSpacing = 40f;

    private const float Padding = 20f;

    private Dictionary<ProtoId<TechnologyPrototype>, ResearchNode> _nodes = new();

    public ResearchTree()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
    }

    public void SetTree(Dictionary<ProtoId<TechnologyPrototype>, ResearchNode> nodes)
    {
        _nodes = nodes;

        NodeCanvas.RemoveAllChildren();
        UpdateSize();

        foreach (var (tech, node) in _nodes)
        {
            var card = new ResearchNodeCard(node);

            NodeCanvas.AddChild(card);
            LayoutContainer.SetPosition(card, GetNodePosition(node));
        }
    }

    private Vector2 GetNodePosition(ResearchNode node)
    {
        return new Vector2(
            Padding + node.UiPosition.X * (NodeWidth + HorizontalSpacing),
            Padding + node.UiPosition.Y * (NodeHeight + VerticalSpacing));
    }

    private void UpdateSize()
    {
        int maxX = 0;
        int maxY = 0;

        foreach (var (tech, node) in _nodes)
        {
            if (node.UiPosition.X > maxX) maxX = node.UiPosition.X;
            if (node.UiPosition.Y > maxY) maxY = node.UiPosition.Y;
        }

        var size = new Vector2(
            Padding + maxX * (NodeWidth + HorizontalSpacing),
            Padding + maxY * (NodeHeight + VerticalSpacing));

        MinSize = size;
        MaxSize = size;
        SetSize = size;
    }
}