using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.ResearchTree;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence14.Research.ResearchTree;

[GenerateTypedNameReferences]
public sealed partial class ResearchTreeWindow : FancyWindow
{
    public ResearchTreeWindow()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(ResearchTreeClientBoundUserInterfaceState state)
    {
        PointsLabel.Text = state.Points.ToString();
    }
}