using Content.Shared._Persistence14.Research.ResearchTree;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence14.Research.ResearchTree;

[GenerateTypedNameReferences]
public sealed partial class ResearchNodeCard : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private ResearchNode? _node;

    public ResearchNodeCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public ResearchNodeCard(ResearchNode node) : this()
    {
        SetNode(node);
    }

    public void SetNode(ResearchNode node)
    {
        _node = node;

        if (!_prototypeManager.TryIndex(node.Technology, out TechnologyPrototype? technology))
            return;

        NameLabel.Text = Loc.GetString(technology.Name);
    }

    public ResearchNode? Node => _node;
}