using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.TechDisk;
using Content.Shared.EntityConditions;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence14.Research.TechDisk;

[GenerateTypedNameReferences]
public sealed partial class TechDiskTerminalWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private ILogManager _log = default!;
    private SpriteSystem _sprite = default!;

    private TechDiskTerminalBUIState? _lastState = null;
    private ProtoId<LatheCategoryPrototype>? _currentCategory = null;
    private readonly List<ProtoId<LatheCategoryPrototype>> _categories = [];

    public TechDiskTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
        var entMan = IoCManager.Resolve<EntityManager>();

        _sprite = entMan.System<SpriteSystem>();

        SearchBar.OnTextChanged += _ => DrawServerTechCards();

        CategoryFilter.OnItemSelected += args =>
        {
            CategoryFilter.SelectId(args.Id);

            if (args.Id == -1)
                _currentCategory = null;
            else
                _currentCategory = _categories[args.Id];

            DrawServerTechCards();
        };
    }

    public void UpdateUIState(TechDiskTerminalBUIState state)
    {
        _lastState = state;

        UpdateCategories();
        DrawServerTechCards();
        DrawDiskTechCards();

        ResearchPointLabel.Text = $"{state.ResearchPoints}";
        PrintCostLabel.Text = $"{state.CurrentResearchPrice}";
        PrintButton.Disabled = !state.CanPrint;

        StorageLabel.Text = $"{state.CurrentTechSize} / {state.MaxTechSize} MB";
        StorageProgress.MaxValue = state.MaxTechSize;
        StorageProgress.Value = state.CurrentTechSize;
    }

    private void UpdateCategories()
    {
        if (_lastState is not { } state)
            return;

        var categories = state.ServerData.Values.Union(state.DiskData.Values)
            .SelectMany(x => x.Categories)
            .Distinct()
            .Select(id => _protoMan.Index(id))
            .OrderBy(x => Loc.GetString(x.Name))
            .ToList();

        _categories.Clear();
        _categories.AddRange(categories.Select(x => (ProtoId<LatheCategoryPrototype>)x));

        CategoryFilter.Clear();
        CategoryFilter.AddItem("All", -1);

        for (int i = 0; i < categories.Count; i++)
        {
            CategoryFilter.AddItem(Loc.GetString(categories[i].Name), i);
        }


        if (_currentCategory == null)
            CategoryFilter.SelectId(-1);
    }

    private void DrawServerTechCards()
    {
        if (_lastState is not { } state)
            return;

        ServerTechList.RemoveAllChildren();

        var techs = state.ServerData.Values.AsEnumerable();
        if (_currentCategory is { } category)
            techs = techs.Where(x => x.Categories.Contains(category));
        if (SearchBar.Text.Trim() != "")
        {
            techs = techs
                .Select(x => (tech: x, score: SearchScore(x.TechName, SearchBar.Text)))
                .Where(x => x.score >= 0.5f)
                .OrderByDescending(x => x.score)
                .Select(x => x.tech);
        }

        foreach (var tech in techs)
        {
            var proto = _protoMan.Index(tech.TechId);
            var canAdd = state.CurrentTechSize + tech.TechSize <= state.MaxTechSize;
            var card = new TechCardControl(TechCardSide.Server, tech, canAdd, false, GetRecipeDisplayControl(proto));
            card.OnAdd += OnAdd;
            ServerTechList.AddChild(card);
        }
    }

    private void DrawDiskTechCards()
    {
        if (_lastState is not { } state)
            return;

        DiskTechList.RemoveAllChildren();

        foreach (var (techId, tech) in state.DiskData)
        {
            var proto = _protoMan.Index(techId);
            var canAdd = state.CurrentTechSize + tech.TechSize <= state.MaxTechSize;
            var card = new TechCardControl(TechCardSide.Disk, tech, canAdd, true, GetRecipeDisplayControl(proto));
            card.OnAdd += OnAdd;
            card.OnRemove += OnRemove;
            DiskTechList.AddChild(card);
        }
    }

    private Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
        {
            var textRect = new TextureRect
            {
                Texture = _sprite.Frame0(recipe.Icon)
            };
            return textRect;
        }

        if (recipe.Result is { } result)
        {
            var entProtoView = new EntityPrototypeView();
            entProtoView.SetPrototype(result);
            return entProtoView;
        }

        return new Control();
    }

    private static float SearchScore(string name, string query)
    {
        var levDist = LevenshteinDistance(name, query);
        var maxLength = Math.Max(name.Length, query.Length);

        return 1.0f - (float)levDist / maxLength;
    }

    private static float LevenshteinDistance(string first, string second)
    {
        var previous = new int[second.Length + 1];
        var current = new int[second.Length + 1];

        for (var j = 0; j <= second.Length; j++)
            previous[j] = j;

        for (var i = 0; i <= first.Length; i++)
        {
            current[0] = i;

            for (var j = 0; j < second.Length; j++)
            {
                var cost = first[i - 1] == second[j - 1] ? 0 : 1;

                current[j] = Math.Min(
                    Math.Min(current[j - 1] + 1, previous[j] + 1),
                    previous[j - 1] + cost
                );


                (previous, current) = (current, previous);
            }
        }

        return previous[second.Length];
    }

    public event Action<ProtoId<LatheRecipePrototype>>? OnAdd;
    public event Action<ProtoId<LatheRecipePrototype>>? OnRemove;
}