using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.TechDisk;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence14.Research.TechDisk;

[GenerateTypedNameReferences]
public sealed partial class TechDiskTerminalWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    private TechDiskTerminalBUIState? _lastState = null;

    public TechDiskTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);

        var latheCategories = _protoMan.EnumeratePrototypes<LatheCategoryPrototype>();
    }

    public void UpdateUIState(TechDiskTerminalBUIState state)
    {
        _lastState = state;

        DrawServerTechCards();
        DrawDiskTechCards();

        ResearchPointLabel.Text = $"{state.ResearchPoints}";
        PrintCostLabel.Text = $"{state.CurrentResearchPrice}";
        PrintButton.Disabled = !state.CanPrint;
    }

    private void DrawServerTechCards()
    {
        if (_lastState is not { } state)
            return;

        ServerTechList.RemoveAllChildren();

        foreach (var (techId, tech) in state.ServerData)
        {
            var canAdd = state.CurrentTechSize + tech.TechSize <= state.MaxTechSize;
            var card = new TechCardControl(TechCardSide.Server, tech, canAdd, false);
            card.OnAdd += OnAdd;
            ServerTechList.AddChild(card);
        }
    }

    private void DrawDiskTechCards()
    {
        if (_lastState is not { } state)
            return;

        DiskTechList.RemoveAllChildren();

        foreach (var (techId, tech) in state.DiskData)
        {
            var canAdd = state.CurrentTechSize + tech.TechSize <= state.MaxTechSize;
            var card = new TechCardControl(TechCardSide.Disk, tech, canAdd, true);
            card.OnAdd += OnAdd;
            card.OnRemove += OnRemove;
            DiskTechList.AddChild(card);
        }
    }

    public event Action<ProtoId<LatheRecipePrototype>>? OnAdd;
    public event Action<ProtoId<LatheRecipePrototype>>? OnRemove;
}