using Content.Shared._Persistence14.Research.TechDisk;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence14.Research.TechDisk;

[GenerateTypedNameReferences]
public sealed partial class TechCardControl : PanelContainer
{
    public readonly ProtoId<LatheRecipePrototype> TechId;

    public TechCardControl()
    {
        RobustXamlLoader.Load(this);
    }

    public TechCardControl(TechCardSide side, TechCardData data, bool canAdd, bool canRemove)
    {
        RobustXamlLoader.Load(this);

        TechId = data.TechId;

        TechNameLabel.Text = data.TechName;
        CountLabel.Text = $"{data.Quantity}";

        RemoveButton.Visible = side == TechCardSide.Disk;

        AddButton.Text = side == TechCardSide.Server ? ">" : "+";
        AddButton.OnPressed += _ => OnAdd?.Invoke(TechId);
        RemoveButton.OnPressed += _ => OnRemove?.Invoke(TechId);

        AddButton.Disabled = !canAdd;
        RemoveButton.Disabled = !canRemove;
    }

    public event Action<ProtoId<LatheRecipePrototype>>? OnAdd;
    public event Action<ProtoId<LatheRecipePrototype>>? OnRemove;
}

public enum TechCardSide
{
    Server,
    Disk
}